apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
        - name: dind-storage
          emptyDir: {}
      containers:
      - name: jenkins
        image: mehrabrahman/pjenkins:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375
      - name: dind
        image: docker:18.03-dind
        securityContext:
            privileged: true
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
        resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
