apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: web-ui
    nodePort: 30200
    port: 8080
    targetPort: 8080
  - name: remote-java-protocol
    nodePort: 30300
    port: 50000
    targetPort: 50000
